/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.*;

import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author mohamed amine tebbin
 */
public class login extends javax.swing.JFrame {
 public Border borderwrong = new LineBorder(Color.RED, 3, true);
  public Border borderright = new LineBorder(Color.white, 0, true);
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logofst.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emailf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        clearbtn = new javax.swing.JButton();
        loginbtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        passwordf = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(26, 18, 11));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Harry P", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Email");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, 24));

        emailf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfActionPerformed(evt);
            }
        });
        jPanel1.add(emailf, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 290, 28));

        jLabel2.setFont(new java.awt.Font("Harry P", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 63, 22));

        clearbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dust.png"))); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 120, 30));

        loginbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login (2).png"))); // NOI18N
        loginbtn.setText("Login");
        loginbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 140, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "responsable", "etudiant", "enseignant", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 134, -1));

        jLabel4.setText("Login as :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 62, 34));

        passwordf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfActionPerformed(evt);
            }
        });
        jPanel1.add(passwordf, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 290, 25));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("forgot password ?");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 130, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/output-onlinepngtools (5).png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfActionPerformed
       
    }//GEN-LAST:event_emailfActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
       emailf.setBorder(borderright);
        passwordf.setBorder(borderright);
        jComboBox1.setBorder(borderright);
        if("".equals(emailf.getText())){
            emailf.setBorder(borderwrong);
       }else if("".equals(passwordf.getText())){
           passwordf.setBorder(borderwrong);
       }else if(jComboBox1.getSelectedItem().toString().equals("none")){
           jComboBox1.setBorder(borderwrong);
          
       } else{
           PreparedStatement ps;
           Connection con = myconnection.getConnection();
           try {
               ps = con.prepareStatement("select * from "+jComboBox1.getSelectedItem().toString()+"  where   login = ? and pwd = ? ");
               ps.setString(1, emailf.getText());
               ps.setString(2, passwordf.getText());
               ResultSet rs = ps.executeQuery();
               int id =0;
               String email="";
               String nom="";
               String prenom="";
               String password="";
               
               while(rs.next()){
                   email=rs.getString("login");
                   nom=rs.getString("nom");
                   prenom=rs.getString("prenom");
                  password =rs.getString("pwd");
                  id = rs.getInt(1);
               }
               if(email.equals(emailf.getText())==false ||password.equals(passwordf.getText()) == false ){
                   JOptionPane.showMessageDialog(rootPane, "invalid input");
                   throw new invalidinput("invalid input");
               }else{
                   System.out.println("hello"+prenom+" "+nom);
                   JOptionPane.showMessageDialog(rootPane,"hello"+" "+prenom+" "+nom);
                   
               }
               if(jComboBox1.getSelectedItem()=="etudiant"){
                       etudiantForm hey = new etudiantForm(id);
                       hey.setVisible(true);
                       hey.pack();
                       hey.setLocationRelativeTo(null);
                       hey.idlab.setText(" id :"+Integer.toString(id));
                       hey.nomlab.setText("nom : "+nom);
                       hey.prenlab.setText("prenom : "+prenom);
                      
                       this.dispose();
                      
                   }else if(jComboBox1.getSelectedItem()=="enseignant"){
                      enseignantForm messi = new enseignantForm(id);
                       messi.setVisible(true);
                       messi.pack();
                       messi.setLocationRelativeTo(null);
                       this.dispose();
                   
                   }else{
                       responsableForm ronaldo = new responsableForm();
                       ronaldo.setVisible(true);
                       ronaldo.pack();
                       ronaldo.setLocationRelativeTo(null);
                       this.dispose();
                   
                   }
            
               
           } catch (SQLException | invalidinput ex) {
              System.err.println(ex.getMessage());
           }
           
           
       }
    }//GEN-LAST:event_loginbtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        emailf.setText("");
        passwordf.setText("");
        jComboBox1.setSelectedIndex(0);
        emailf.setBorder(borderright);
        passwordf.setBorder(borderright);
        jComboBox1.setBorder(borderright);
    }//GEN-LAST:event_clearbtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void passwordfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
         forgotPassword hey = new forgotPassword();
          hey.setVisible(true);
          hey.pack();
          hey.setLocationRelativeTo(null);
          this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearbtn;
    private javax.swing.JTextField emailf;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField passwordf;
    // End of variables declaration//GEN-END:variables
}
