
import javax.mail.PasswordAuthentication;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mohamed amine tebbin
 */
public class responsableForm extends javax.swing.JFrame {

    /**
     * Creates new form responsableForm
     */
    public responsableForm() {
        initComponents();
        responsable.getlibmat(jComboBox1);
        responsable.getfil(jComboBox3);
         responsable.getMat(jComboBox2);
        charts.setVisible(false);
        email.setVisible(false);
        cancel.setVisible(false);
        ab.setVisible(false);
        responsable.getfil(jComboBox4);
        responsable.getnv(jComboBox5);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        chartslab = new javax.swing.JLabel();
        ablab = new javax.swing.JLabel();
        cancellab = new javax.swing.JLabel();
        emaillab = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        charts = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        email = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cancel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        ab = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField12 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        chartslab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pie-chart.png"))); // NOI18N
        chartslab.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.black, java.awt.Color.darkGray));
        chartslab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chartslabMouseClicked(evt);
            }
        });
        jPanel1.add(chartslab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 40, 40));

        ablab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/student.png"))); // NOI18N
        ablab.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.black, java.awt.Color.darkGray));
        ablab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ablabMouseClicked(evt);
            }
        });
        jPanel1.add(ablab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 40, 40));

        cancellab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/multiply.png"))); // NOI18N
        cancellab.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.black, java.awt.Color.darkGray));
        cancellab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancellabMouseClicked(evt);
            }
        });
        jPanel1.add(cancellab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 40, 40));

        emaillab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mail.png"))); // NOI18N
        emaillab.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.black, java.awt.Color.darkGray));
        emaillab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emaillabMouseClicked(evt);
            }
        });
        jPanel1.add(emaillab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 40, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-logout-rounded-down-30.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 588));

        jButton2.setText("genere");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));

        jLabel2.setText("filière :");

        jLabel3.setText("niveau :");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));

        javax.swing.GroupLayout chartsLayout = new javax.swing.GroupLayout(charts);
        charts.setLayout(chartsLayout);
        chartsLayout.setHorizontalGroup(
            chartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartsLayout.createSequentialGroup()
                .addGroup(chartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chartsLayout.createSequentialGroup()
                        .addGap(481, 481, 481)
                        .addGroup(chartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(61, 61, 61)
                        .addGroup(chartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox4, 0, 206, Short.MAX_VALUE)
                            .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(chartsLayout.createSequentialGroup()
                        .addGap(634, 634, 634)
                        .addComponent(jButton2)))
                .addContainerGap(602, Short.MAX_VALUE))
        );
        chartsLayout.setVerticalGroup(
            chartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartsLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(chartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(chartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jButton2)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        getContentPane().add(charts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 590));

        email.setBackground(new java.awt.Color(0, 0, 0));
        email.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("send email");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        email.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 437, 148, 54));

        jLabel23.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("enoyer un email d'alerte ");
        email.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 312, 46));
        email.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 136, 343, 40));

        jLabel24.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("id_etudiant");
        email.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 135, 162, 40));
        email.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 195, 343, 40));

        jLabel25.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("message");
        email.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 253, 162, 40));

        jLabel26.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("subject");
        email.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 194, 162, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        email.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 261, 343, 158));

        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 590));

        cancel.setBackground(new java.awt.Color(0, 0, 0));
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Harry P", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("effacer une absence ");
        cancel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 318, 45));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        cancel.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 107, 301, 37));

        jLabel18.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("id_etudiant");
        cancel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 106, 107, 37));
        cancel.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 163, 301, 37));

        jLabel19.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("id_enseignant");
        cancel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 162, 141, 37));
        cancel.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 219, 301, 37));

        jLabel20.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("numseance");
        cancel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 218, 107, 37));
        cancel.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 332, 301, 37));

        jLabel21.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("date");
        cancel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 331, 107, 37));

        jLabel22.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("matière");
        cancel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 271, 107, 37));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));
        cancel.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 268, 301, 45));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("effacer");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        cancel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 300, 60));

        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 1340, 590));

        ab.setBackground(new java.awt.Color(18, 18, 18));
        ab.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id etudiant", "nom_prenom", "libelle matière", "classe", "fillère", "id enseignant", "nom_prenom_enseignant", "date_absence"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("id etudiant");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("id enseignant");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("numseance");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("date");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("niveau");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/printer.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("libelle");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("fillère");

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("id_classe");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));

        javax.swing.GroupLayout abLayout = new javax.swing.GroupLayout(ab);
        ab.setLayout(abLayout);
        abLayout.setHorizontalGroup(
            abLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(abLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton1))
            .addGroup(abLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        abLayout.setVerticalGroup(
            abLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(abLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(abLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addGroup(abLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(abLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(abLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(ab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
      MessageFormat header= new MessageFormat("liste des absence");
      MessageFormat footer= new MessageFormat("Page{0,number,integer}");
      try{
          jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer);
          
      }catch(Exception e){
          JOptionPane.showMessageDialog(rootPane,e.getMessage());
      }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        responsable.searchabsence(Integer.parseInt(jTextField6.getText()),Integer.parseInt(jTextField7.getText()) ,Integer.parseInt(jTextField8.getText()) ,jComboBox2.getSelectedItem().toString() ,jTextField9.getText());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String  res = student.getLogin(Integer.parseInt(jTextField10.getText())); 
        
      Properties prop = new Properties();
    prop.put("mail.smtp.user","mohamedtebbini047@gmail.com"); 
prop.put("mail.smtp.host", "smtp.gmail.com"); 
prop.put("mail.smtp.port", "25"); 
//prop.put("mail.debug", "true"); 
prop.put("mail.smtp.auth", "true"); 
prop.put("mail.smtp.starttls.enable","true"); 
prop.put("mail.smtp.EnableSSL.enable","true");
prop.put("mail.smtp.password", "wxgepwdngzqenmyj");

prop.setProperty("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");   
prop.setProperty("mail.smtp.socketFactory.fallback", "false");   
prop.setProperty("mail.smtp.port", "465");   
prop.setProperty("mail.smtp.socketFactory.port", "465"); 
                Session session;
        session = Session.getInstance(prop, new javax.mail.Authenticator() {
            
            protected PasswordAuthentication getPasswordAuthentication() {

                return new PasswordAuthentication("mohamedtebbini047@gmail.com", "wxgepwdngzqenmyj");

            }
            
        });
        try{
            System.out.println(res);
        MimeMessage message = new MimeMessage(session);
        message.setFrom(new InternetAddress("mohametebbini047@gmail.com"));
        message.addRecipient(Message.RecipientType.TO, new InternetAddress(res));
        message.setSubject(jTextField11.getText());
        message.setText(jTextArea1.getText());
            Transport.send(message);
            JOptionPane.showMessageDialog(rootPane,"email sent");
        }catch(Exception ex){
            System.err.println(ex.getMessage());
            JOptionPane.showMessageDialog(rootPane,ex.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
            int rowCount = dm.getRowCount();

for (int i = rowCount - 1; i >= 0; i--) {
    dm.removeRow(i);
}
        responsable.search(jTable1,jTextField13.getText() , jComboBox3.getSelectedItem().toString() ,jComboBox1.getSelectedItem().toString() ,jTextField12.getText() ,jTextField4.getText() ,jTextField3.getText() ,jTextField2.getText() ,jTextField1.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if(jPanel1.getBounds().width==60){
        jPanel1.setBounds(jPanel1.getBounds().x,jPanel1.getBounds().y, 100,jPanel1.getBounds().height);
            ablab.setBounds(ablab.getBounds().x, ablab.getBounds().y, 100, ablab.getBounds().height);
            chartslab.setBounds(chartslab.getBounds().x, chartslab.getBounds().y, 100, chartslab.getBounds().height);
             cancellab.setBounds(cancellab.getBounds().x, cancellab.getBounds().y, 100, cancellab.getBounds().height);
            emaillab.setBounds(emaillab.getBounds().x, emaillab.getBounds().y, 100, emaillab.getBounds().height);
             ablab.setText("absence");
             cancellab.setText("cancel");
             emaillab.setText("send mail");
             chartslab.setText("charts");
        
        
        }  else{
            jPanel1.setBounds(jPanel1.getBounds().x,jPanel1.getBounds().y, 60,jPanel1.getBounds().height);
            ablab.setBounds(ablab.getBounds().x, ablab.getBounds().y, 24, ablab.getBounds().height);
            chartslab.setBounds(chartslab.getBounds().x, chartslab.getBounds().y, 24, chartslab.getBounds().height);
             cancellab.setBounds(cancellab.getBounds().x, cancellab.getBounds().y, 24, cancellab.getBounds().height);
            emaillab.setBounds(emaillab.getBounds().x, emaillab.getBounds().y, 24, emaillab.getBounds().height);
           ablab.setText("");
             cancellab.setText("");
             emaillab.setText("");
             chartslab.setText("");
        }  
       
    }//GEN-LAST:event_jLabel1MouseClicked

    private void ablabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ablabMouseClicked
        ab.setVisible(!ab.isVisible());
        email.setVisible(false);
        cancel.setVisible(false);
        charts.setVisible(false);
        
        
    }//GEN-LAST:event_ablabMouseClicked

    private void cancellabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancellabMouseClicked
       cancel.setVisible(!ab.isVisible());
        email.setVisible(false);
        ab.setVisible(false);
        charts.setVisible(false);
    }//GEN-LAST:event_cancellabMouseClicked

    private void emaillabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emaillabMouseClicked
        email.setVisible(!ab.isVisible());
        ab.setVisible(false);
        cancel.setVisible(false);
        charts.setVisible(false);
    }//GEN-LAST:event_emaillabMouseClicked

    private void chartslabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chartslabMouseClicked
        charts.setVisible(!ab.isVisible());
        email.setVisible(false);
        cancel.setVisible(false);
        ab.setVisible(false);
    }//GEN-LAST:event_chartslabMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        responsable rs = new responsable();
        rs.getinfos(jComboBox4.getSelectedItem().toString(), jComboBox5.getSelectedItem().toString());
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        System.out.println(rs.co);
        System.out.println(rs.coo);
        pieDataset.setValue("les etudiant present",Math.abs(rs.co-rs.coo));
        pieDataset.setValue("les etudiant absent", rs.coo);
        JFreeChart chart = ChartFactory.createPieChart("taux d'absences", pieDataset);
        PiePlot p = (PiePlot) chart.getPlot();
        //p.setForegroundAlpha(TOP_ALIGNMENT);
        ChartFrame frame= new ChartFrame("taux d'absence",chart);
        frame.setVisible(true);
        frame.setSize(450, 500);
    

   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        test.logout(this);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(responsableForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(responsableForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(responsableForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(responsableForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new responsableForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ab;
    private javax.swing.JLabel ablab;
    private javax.swing.JPanel cancel;
    private javax.swing.JLabel cancellab;
    private javax.swing.JPanel charts;
    private javax.swing.JLabel chartslab;
    private javax.swing.JPanel email;
    private javax.swing.JLabel emaillab;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
